spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/erp
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 9093

jwt:
  auth:
    converter:
      resource-id: esprit
      principle-attribute: preferred_username


keycloak:
  auth-server-url: http://localhost:8180/
  realm: erp
  resource: esprit
  credentials:
    secret:

admin:
  username: admin
  password: admin